---
# this'll install what you need for it to work

- name: install package requirements
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python-pip
    - python3-bs4
    - python3-requests
    - python3-lxml